---
- name: zfs-zed | Assert that system manager is systemd
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd."
    quiet: "true"
- name: snmpd | Add the OS specific varibles
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"