---
- name: zfs | Execute set-zfs-scan-defaults.sh script
  ansible.builtin.shell: "{{ hostvars[inventory_hostname]['zfs_dest'] }}/set-zfs-scan-defaults.sh"
  args:
    executable: /bin/bash
  become: yes
  when:
    - zfs_help is defined
    - zfs_help | length > 0
    - zfs_help[0].enabled == 'true'
  register: script_output
  failed_when: script_output.rc != 0
